%% Assignment 2 - JD Herlehy || Jacky Li
%% Feb.29.2024
%% Creating a convolution network for the task of image classification

%% using CIFAR10 dataset
OrganizeData;

options = trainingOptions('sgdm', ...
    'MiniBatchSize', 64, ...
    'MaxEpochs',20,...
    'InitialLearnRate',1e-4, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropFactor', 0.2000, ...
    'LearnRateDropPeriod', 5, ...
    'Verbose',false, ...
    'Plots','training-progress');


layers = [
    imageInputLayer([32 32 3]) ...
    convolution2dLayer(3,8, 'Padding','same') ...
    batchNormalizationLayer
    reluLayer ...
    convolution2dLayer(3,10, 'Padding','same') ...
    batchNormalizationLayer
    reluLayer ...
    convolution2dLayer(3,25, 'Padding','same') ...
    batchNormalizationLayer
    reluLayer ...
    convolution2dLayer(3,30, 'Padding','same') ...
    batchNormalizationLayer
    reluLayer ...
    convolution2dLayer(3,35, 'Padding','same') ...
    batchNormalizationLayer
    reluLayer ...
    fullyConnectedLayer(10) ...
    classificationLayer];


net = trainNetwork(TrainingTable, layers, options);